version: '3'

services:
  db:
    image: postgres:14.4
    restart: always
    ports:
      - '5435:5432'
    environment:
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    container_name: shopDB
    volumes:
      - ./postgres:/var/lib/postgresql/data
